export interface Person {
    'Age Range': string,
    'Name': string,
    'CheckIn Individually': string,
    'CheckIn Interpersonally': string,
    'CheckIn Overall': string,
    'CheckIn Social': string,
    'CheckOut Individually': string,
    'CheckOut Interpersonally': string,
    'CheckOut Overall': string,
    'CheckOut Social': string,
    'Cohort': string,
    'Date': string,
    'For Facil - Communicate well with the group':string,
    'For Facil - Create a space that made us feel safe to share': string,
    'For Facil - Empower us to support one another': string,
    'For Facil - Engage the group effectively': string,
    'For Facil - Facilitate learning through reflections': string,
    'For Facil - Have the necessary knowledge and skills for the role': string,
    'For Facil - Invite and embrace all perspectives': string,
    'For Facil - Kindly share with us why you gave the above ratings': string,
    "For Facil - Please write your Growth Facilitator's Name": string,
    'For Facil - Provide useful insights': string,
    'For Group - Efforts, Care & Support and Role': string,
    'For Group - My group members are supportive of one another': string,
    "For Group - What went well in today's session? What else do you appreciate? What do you think contributed to that?": string,
    'For Self - I am inspired and encouraged': string,
    'For Self - I feel I understand myself better': string,
    'For Self - I feel heard and understood': string,
    'For Self - I felt engaged during today’s session': string,
    'For Self - I have gained new perspectives or Ideas':string,
    'For Self - I have learned or practiced skills that is applicable to my daily life': string,
    'For Self - I was able to think deeper because of questions asked': string,
    'For Self - On a scale of 0-10, how satisfied are you with today’s Growth Circle?': string,
    'For Self - Overall, I have benefitted from the session': string,
    'Gender': string,
    'Growth Journey': string,
    'Location': string,
    'Organisation': string,
    'Session Role': string,
    'Topic':string,
    'Times Attended Onboarding':string,
    'Growthcircle Name':string
}